/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_albemuth_jcuda_jcusegsort_KeyValueSortContext */

#ifndef _Included_ru_albemuth_jcuda_jcusegsort_KeyValueSortContext
#define _Included_ru_albemuth_jcuda_jcusegsort_KeyValueSortContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_albemuth_jcuda_jcusegsort_KeyValueSortContext
 * Method:    init
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_ru_albemuth_jcuda_jcusegsort_KeyValueSortContext_init
    (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     ru_albemuth_jcuda_jcusegsort_KeyValueSortContext
 * Method:    free
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ru_albemuth_jcuda_jcusegsort_KeyValueSortContext_free
    (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
